apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-repo.fullname" . }}
  labels:
    {{- include "my-repo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-repo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-repo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "my-repo.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
              {{- end }}
